---
kind: BundleNamespaceMapping
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: fleet-all-clusters-bundle
  namespace: fleet-all-clusters-bundle
bundleSelector:
  matchLabels:
    env: all
namespaceSelector:
  matchExpressions:
    - {key: env, operator: In, values: [tools, qa, prod]}
---
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: all-chart-d
  namespace: fleet-all-clusters-bundle
  labels:
    env: all
spec:
  repo: https://github.com/rancher/fleet-examples.git
  paths:
  - charts/D
  branch: main
  targets:
  - name: all
    clusterSelector: {}
---
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: tools-chart-a-b
  namespace: fleet-tools
spec:
  repo: https://github.com/rancher/fleet-examples.git
  paths:
  - charts/A
  - charts/B
  branch: main
  targets:
  - name: tools
  - name: all
    clusterSelector: {}
---
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: qa-chart-c
  namespace: fleet-qa
spec:
  repo: https://github.com/rancher/fleet-examples.git
  paths:
  - charts/C
  branch: main
  targets:
  - name: all
    clusterSelector: {}
